### ISSUE TITLE
Investigate Chrome interface requirements

### ISSUE THREAD

**Issue by nejdaw** [Viridovix/show-me-the-code-github#5]
We need to understand:
- what are the requirements for the Chrome plugins in terms of language / libraries used
- how should the plugin be build and delivered

**Comment by balawama** [comment]
##### Supported languages / libraries

JavaScript and everything based on it.
I've found scala.js based extension (http://github.com/lucidd/scala-js-chrome) but there seem to be no usages of it

**Comment by balawama** [comment]
##### Plugin delivery (dev)
- Manual installation from disk https://developer.chrome.com/apps/first_app#five 
- Installation from cmd `--load-and-launch-app=/path/to/app`
- Launch of new instance with reloaded content `--app-id=ajjhbohkjpincjgiieeomimlgnll`

**Comment by nejdaw** [comment]
@balawama the scala.js extension looks nice, although I imagine we wouldn't need mappings for every function call in API, so we could implement the bindings ourselves instead of using this extension. One important thing that was noted in [known issues](https://github.com/lucidd/scala-js-chrome#known-issues) is that scala.js compiles everything to one JS file, whereas usually you need several small JS files for separate functions. I don't know if that would be an issue for us.

**Supported languages / libraries**
I have heard that some people are using [Babel](https://babeljs.io/) - which compiles ECMAScript6 (2015) to ECMAScript 5 (2009). So we could write in the newest JS version without worrying for browser support.

**Comment by balawama** [comment]
What technologies are used to write extensions for Chrome?

Extensions are written using the same standard web technologies that developers use to create websites. HTML is used as a content markup language, CSS is used for styling, and JavaScript for scripting. Because Chrome supports HTML5 and CSS3, developers can use the latest open web technologies such as canvas and CSS animations in their extensions. Extensions also have access to several JavaScript APIs that help perform functions like JSON encoding and interacting with the browser.

**Comment by balawama** [comment]
So it looks like that we can use any js-based library.
Do we need to learn anything more in context of this task?

**Comment by balawama** [comment]
btw nice faq available here:
https://developer.chrome.com/apps/faq

**Comment by nejdaw** [comment]
I think that you can close this task. We know all we need. Now we can work on #6 and everyone can make their proposals regarding technology stack.
